apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-app.fullname" . }}-gradio
  labels:
    {{- include "ai-app.labels" . | nindent 4 }}
    component: gradio
spec:
  type: {{ .Values.gradio.service.type }}
  ports:
    - port: {{ .Values.gradio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-app.selectorLabels" . | nindent 4 }}
    component: gradio
